general:
  kafka-topic: trader-updates

server:
  port: 33400

spring:
  kafka:
    bootstrap-servers: "localhost:9092"
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: "jpmc-midas"
      properties:
        spring.json.trusted.packages: "com.jpmc.midascore.foundation"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer